[project]
name = "pyneapple-gpufit"
version = "0.2.0"
description = "GPU-accelerated solvers for Pyneapple using pygpufit."
authors = [
    {name = "Thomas Thiel", email = "thomas.thiel@hhu.de"}
]
maintainters = [
    {name = "Thomas Thiel", email = "thomas.thiel@hhu.de"}
]
readme = "README.md"
requires-python = ">=3.12"
license = { text = "GPL-3.0-or-later" }
dependencies = [
    "loguru",
    "numpy>=2.0",
    "pyneapple>=2.0.0",
]

[project.entry-points."pyneapple.solvers"]
gpufit_curvefit = "pyneapple_gpufit:GpuCurveFitSolver"
gpufit_nnls = "pyneapple_gpufit:GpuNNLSSolver"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["pyneapple_gpufit"]
artifacts = [
    "pyneapple_gpufit/_vendor/pygpufit/Gpufit.dll",
    "pyneapple_gpufit/_vendor/pygpufit/libGpufit.so",
]

[tool.uv.sources]
pyneapple = { git = "https://github.com/darksim33/Pyneapple.git", rev = "v2.0.0" }

[dependency-groups]
dev = [
    "pytest>=8.0",
    "pytest-mock>=3.14",
    "pytest-cov>=6.0",
    "ruff>=0.15",
]


[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = [
    "-v",
    "--cov=pyneapple_gpufit",
    "--cov-report=html",
    "--cov-report=term-missing"
]
